In [2]:
import os
for dirname, _, filenames in os.walk('./'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


./sample_submission.csv
./train.csv
./house.ipynb
./test.csv
./house-prices-advanced-regression-techniques.zip
./data_description.txt
./.ipynb_checkpoints/house-checkpoint.ipynb


In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('./train.csv')

In [5]:
df.shape

(1460, 81)

In [7]:
df.head(2)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  

[2 rows x 81 columns]

In [10]:
cat ./data_description.txt

MSSubClass: Identifies the type of dwelling involved in the sale.	

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.
		
       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park 
       RM

In [11]:
df=pd.read_csv('./train.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"])

In [12]:
df.shape

(1460, 10)

In [13]:
df.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage    259
LotArea          0
Street           0
LotShape         0
YearBuilt        0
1stFlrSF         0
2ndFlrSF         0
SalePrice        0
dtype: int64

In [18]:
df['LotFrontage'].value_counts(dropna=False).sort_values()

144.0      1
106.0      1
150.0      1
137.0      1
46.0       1
        ... 
50.0      57
80.0      69
70.0      70
60.0     143
NaN      259
Name: LotFrontage, Length: 111, dtype: int64

In [19]:
df['LotFrontage'].fillna((df['LotFrontage'].mean()),inplace=True)

In [20]:
df['LotFrontage'].value_counts(dropna=False)

70.049958     259
60.000000     143
70.000000      70
80.000000      69
50.000000      57
             ... 
112.000000      1
138.000000      1
149.000000      1
38.000000       1
111.000000      1
Name: LotFrontage, Length: 111, dtype: int64

In [21]:
df.head(20)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0           60       RL    65.000000     8450   Pave      Reg       2003   
1           20       RL    80.000000     9600   Pave      Reg       1976   
2           60       RL    68.000000    11250   Pave      IR1       2001   
3           70       RL    60.000000     9550   Pave      IR1       1915   
4           60       RL    84.000000    14260   Pave      IR1       2000   
5           50       RL    85.000000    14115   Pave      IR1       1993   
6           20       RL    75.000000    10084   Pave      Reg       2004   
7           60       RL    70.049958    10382   Pave      IR1       1973   
8           50       RM    51.000000     6120   Pave      Reg       1931   
9          190       RL    50.000000     7420   Pave      Reg       1939   
10          20       RL    70.000000    11200   Pave      Reg       1965   
11          60       RL    85.000000    11924   Pave      IR1       2005   
12          20       RL    70.049958    12968   Pave      IR2       1962   
13          20       RL    91.000000    10652   Pave      IR1       2006   
14          20       RL    70.049958    10920   Pave      IR1       1960   
15          45       RM    51.000000     6120   Pave      Reg       1929   
16          20       RL    70.049958    11241   Pave      IR1       1970   
17          90       RL    72.000000    10791   Pave      Reg       1967   
18          20       RL    66.000000    13695   Pave      Reg       2004   
19          20       RL    70.000000     7560   Pave      Reg       1958   

    1stFlrSF  2ndFlrSF  SalePrice  
0        856       854     208500  
1       1262         0     181500  
2        920       866     223500  
3        961       756     140000  
4       1145      1053     250000  
5        796       566     143000  
6       1694         0     307000  
7       1107       983     200000  
8       1022       752     129900  
9       1077         0     118000  
10      1040         0     129500  
11      1182      1142     345000  
12       912         0     144000  
13      1494         0     279500  
14      1253         0     157000  
15       854         0     132000  
16      1004         0     149000  
17      1296         0      90000  
18      1114         0     159000  
19      1339         0     139000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1460 non-null   int64  
 1   MSZoning     1460 non-null   object 
 2   LotFrontage  1460 non-null   float64
 3   LotArea      1460 non-null   int64  
 4   Street       1460 non-null   object 
 5   LotShape     1460 non-null   object 
 6   YearBuilt    1460 non-null   int64  
 7   1stFlrSF     1460 non-null   int64  
 8   2ndFlrSF     1460 non-null   int64  
 9   SalePrice    1460 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 114.2+ KB


In [23]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique())))

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 111
Column name LotArea and unique values are 1073
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 753
Column name 2ndFlrSF and unique values are 417
Column name SalePrice and unique values are 663


In [24]:
# Today's date
import datetime
datetime.datetime.now().year

2021

In [25]:
# How old is the building.
df['Total Years']=datetime.datetime.now().year- df['YearBuilt']

In [26]:
df.drop("YearBuilt", axis= 1, inplace = True)

In [27]:
# Creating Categorical features.
categorical_features=["MSSubClass", "MSZoning", "Street", "LotShape"]
out_feature="SalePrice"

In [28]:
# print the uniques value of each categorical_features.
print(df['MSSubClass'].unique(),
df['MSZoning'].unique(),
df['Street'].unique(),
df['LotShape'].unique())

[ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40] ['RL' 'RM' 'C (all)' 'FV' 'RH'] ['Pave' 'Grvl'] ['Reg' 'IR1' 'IR2' 'IR3']


In [29]:
# For example- Use label encoding for MSSubClass.
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
# label_encoder object knows how to understand word labels. 
lbl_encoders["MSSubClass"]=LabelEncoder()
# Encode labels in column 'MSSubclass'.
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0])

In [30]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [31]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
# Apply Label encoding for every faeature in categorical feature list.
for feature in categorical_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature])

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1460 non-null   int64  
 1   MSZoning     1460 non-null   int64  
 2   LotFrontage  1460 non-null   float64
 3   LotArea      1460 non-null   int64  
 4   Street       1460 non-null   int64  
 5   LotShape     1460 non-null   int64  
 6   1stFlrSF     1460 non-null   int64  
 7   2ndFlrSF     1460 non-null   int64  
 8   SalePrice    1460 non-null   int64  
 9   Total Years  1460 non-null   int64  
dtypes: float64(1), int64(9)
memory usage: 114.2 KB


In [33]:
df.head(5)

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           18  
1         0     181500           45  
2       866     223500           20  
3       756     140000          106  
4      1053     250000           21

In [34]:
df['MSSubClass'].unique()

array([ 5,  0,  6,  4, 14,  3, 10, 11,  1,  9,  8, 12,  7, 13,  2])

In [42]:
import numpy as np
categorical_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
categorical_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [43]:
categorical_features.shape

(1460, 4)

In [44]:
import torch
categorical_features=torch.tensor(categorical_features,dtype=torch.int64)
categorical_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [45]:
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        # SalePrice is also included cause it is a dependent feature.
        # The pass statement in Python is used when a statement is required syntactically but you do not want any command or code to execute. The pass statement is a null operation; nothing happens when it executes.
        pass
    else:
        cont_features.append(i)

In [46]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [47]:
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    18.],
        [   80.,  9600.,  1262.,     0.,    45.],
        [   68., 11250.,   920.,   866.,    20.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    80.],
        [   68.,  9717.,  1078.,     0.,    71.],
        [   75.,  9937.,  1256.,     0.,    56.]])

In [48]:
cont_values

tensor([[   65.,  8450.,   856.,   854.,    18.],
        [   80.,  9600.,  1262.,     0.,    45.],
        [   68., 11250.,   920.,   866.,    20.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    80.],
        [   68.,  9717.,  1078.,     0.,    71.],
        [   75.,  9937.,  1256.,     0.,    56.]])

In [49]:
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [51]:
# Categorical dimension - the array contains no. of unique values for each feature.
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]]

In [52]:
embedding_dim= [(x, min(50, (x+1 ) // 2)) for x in cat_dims]

In [53]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F
# nn.Embedding - This module is often used to store word embeddings and retrieve them using indices. The input to the module is a list of indices, and the output is the corresponding word embeddings.
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
# embedding layer 
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [55]:
categorical_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [58]:
# display.max_rows:
#       Displays the default number of value. Interpreter reads this value and displays the rows with this value as upper limit to display.
pd.set_option('display.max_rows', 500)
# Create a null list. It will store the indices of a value of columns of tensor. 
embedding_val=[]
# Here i represent the column of tensor. In categorical_feature each column represent its respective feature.
# 'e' coverts the input size of embedding layer to the require output size.
#Enumerate() method adds a counter to an iterable and returns it in a form of enumerate object. This enumerate object can then be used directly in for loops or be converted into a list of tuples using list() method.
for i,e in enumerate(embed_representation):
    print(i,e)
    embedding_val.append(e(categorical_features[:,i]))

0 Embedding(15, 8)
1 Embedding(5, 3)
2 Embedding(2, 1)
3 Embedding(4, 2)


In [61]:
categorical_features[:,0]

tensor([5, 0, 5,  ..., 6, 0, 0])

In [64]:
 embedding_val

[tensor([[-0.7222,  1.7136, -0.2260,  ..., -0.3020,  0.7737,  1.8005],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676],
         [-0.7222,  1.7136, -0.2260,  ..., -0.3020,  0.7737,  1.8005],
         ...,
         [ 0.1075, -1.3904,  0.4018,  ..., -0.0852,  1.7499,  0.2883],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676]],
        grad_fn=<EmbeddingBackward>),
 tensor([[-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         ...,
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709]], grad_fn=<EmbeddingBackward>),
 tensor([[-0.9110],
         [-0.9110],
         [-0.9110],
         ...,
         [-0.9110],
         [-0.9110],
         [-0.9110]], grad_fn=<EmbeddingBackward>),
 tensor([[ 1.3745, -0.4000],
         [ 1.3745, -0.4000],
         [-0.1268, -0.626

In [65]:
cat_featuresz=categorical_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [67]:
# Print the embedded values.
embedding_val

[tensor([[-0.7222,  1.7136, -0.2260,  ..., -0.3020,  0.7737,  1.8005],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676],
         [-0.7222,  1.7136, -0.2260,  ..., -0.3020,  0.7737,  1.8005],
         ...,
         [ 0.1075, -1.3904,  0.4018,  ..., -0.0852,  1.7499,  0.2883],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676],
         [-1.0948,  0.7546, -2.6226,  ..., -2.0761, -1.1142, -0.3676]],
        grad_fn=<EmbeddingBackward>),
 tensor([[-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         ...,
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709],
         [-1.7360,  0.7808,  0.5709]], grad_fn=<EmbeddingBackward>),
 tensor([[-0.9110],
         [-0.9110],
         [-0.9110],
         ...,
         [-0.9110],
         [-0.9110],
         [-0.9110]], grad_fn=<EmbeddingBackward>),
 tensor([[ 1.3745, -0.4000],
         [ 1.3745, -0.4000],
         [-0.1268, -0.626

In [68]:
# Arrange the 4 tensors in one tensor in 4 column. Concatenating the 4 tensors.
z = torch.cat(embedding_val, 1)
z

tensor([[-0.7222,  1.7136, -0.2260,  ..., -0.9110,  1.3745, -0.4000],
        [-1.0948,  0.7546, -2.6226,  ..., -0.9110,  1.3745, -0.4000],
        [-0.7222,  1.7136, -0.2260,  ..., -0.9110, -0.1268, -0.6267],
        ...,
        [ 0.1075, -1.3904,  0.4018,  ..., -0.9110,  1.3745, -0.4000],
        [-1.0948,  0.7546, -2.6226,  ..., -0.9110,  1.3745, -0.4000],
        [-1.0948,  0.7546, -2.6226,  ..., -0.9110,  1.3745, -0.4000]],
       grad_fn=<CatBackward>)

In [69]:
# Implement dropupout
droput=nn.Dropout(.4)

In [70]:
# Perform the dropout on concatenated tensor i.e z
final_embed=droput(z)
final_embed

tensor([[-1.2036,  0.0000, -0.0000,  ..., -0.0000,  0.0000, -0.6666],
        [-1.8246,  0.0000, -0.0000,  ..., -0.0000,  0.0000, -0.0000],
        [-1.2036,  0.0000, -0.3766,  ..., -1.5183, -0.2114, -0.0000],
        ...,
        [ 0.0000, -0.0000,  0.0000,  ..., -0.0000,  0.0000, -0.0000],
        [-0.0000,  1.2577, -0.0000,  ..., -1.5183,  0.0000, -0.6666],
        [-0.0000,  0.0000, -4.3710,  ..., -0.0000,  2.2908, -0.6666]],
       grad_fn=<MulBackward0>)

In [71]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [72]:
# Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
# Define a class for model.
class FeedForwardNN(nn.Module):
    
    # function contains embedding dimension, no. of continuous values, output, layers and dropout value.
    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        # Create a module list for embedding layers.
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        # n_emb = embedding dimension, n_cont = no.of continuous values.
        n_emb = sum((out for inp,out in embedding_dim))
        # n_in = input.
        n_in = n_emb + n_cont
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            # Since our input is a 1D array we will use BatchNorm1d class present in the Pytorch nn module.
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        # emedding the categorical features.
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x